### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by dbrgn** [py3minepi/py3minepi-legacy#13]
I'd suggest that we start to use Pytest as a testing platform: http://pytest.org/ I've made _very_ good experiences with it.

If you agree, I could add the configuration for a nice test suite (including style checks).

Things like a mocked Minecraft server could be added as testing fixtures.

**Comment by pozorvlak** [comment]
The (currently broken) [continuous integration build](https://github.com/py3minepi/py3minepi/blob/master/.travis-ci.sh) already assumes we're using pytest, so yeah, go for it :-)

**Comment by ghickman** [comment]
@dbrgn – Yes please! As @pozorvlak said we've already started down that road (I wholeheartedly agree with you on pytest).

To give you some direction, the plan is to try and build up a test suite for the new Pythonic API while also having one for the lower level code where the backwards compatibility will come in so we can try and catch regressions there.
