### ISSUE TITLE
GitHub Organisation avatar

### ISSUE THREAD

**Issue by bennuttall** [py3minepi/py3minepi-legacy#39]
I'm not an owner of the org, so can't upload an avatar.

I suggest this:

![](http://i.imgur.com/E5SC4yM.png)

(I expanded width to make it square to avoid cropping)

**Comment by doismellburning** [comment]
I defer to you on the IP matter; on the assumption that you have that in-hand, done :)

**Comment by doismellburning** [comment]
(If anyone has the skills to sort transparency, please...)

**Comment by doismellburning** [comment]
I ran it through `convert` with `-fuzz 5% -transparent white` which seems to have mostly done the job:

![transparent](https://cloud.githubusercontent.com/assets/817118/4490080/80609c46-4a25-11e4-9d36-eb730f8334ee.png)

**Comment by pozorvlak** [comment]
:+1:

**Comment by doismellburning** [comment]
@bennuttall Look good to you? If so lets close :)

**Comment by bennuttall** [comment]
:+1:
