### ISSUE TITLE
Python 2/3 Policy

### ISSUE THREAD

**Issue by dbrgn** [py3minepi/py3minepi-legacy#45]
Do we want Python 2.7 compatibility?

If yes, we'd need to make a few fixes. First of all there are a few new-style classes that should inherit from `object`:

```
danilo@adalbert:py3minepi$ grep -RE "class [^\(]*(:|\(\))" minecraft/ tests/
minecraft/connection.py:class Connection:
minecraft/block.py:class Block:
minecraft/vec3.py:class Vec3:
minecraft/minecraft.py:class CmdPositioner:
minecraft/minecraft.py:class CmdCamera:
minecraft/minecraft.py:class CmdEvents:
minecraft/minecraft.py:class Minecraft:
minecraft/event.py:class BlockEvent:
tests/test_vec3.py:class TestVec3():
tests/test_event.py:class TestEvent():
```

Furthermore we should have an encoding declaration at the top of every Python file as well as a sensible set of future imports. I'd suggest the following:

``` python
# -*- coding: utf-8 -*-
from __future__ import print_function, division, absolute_import, unicode_literals
```

See http://stackful-dev.com/quick-tips-on-making-your-code-python-3-ready.html.

**Comment by doismellburning** [comment]
Yes. Compatibility is a priority. We do not want to break existing code + learning materials.

**Comment by doismellburning** [comment]
(And I think you mean "there are a few old-style classes"!)

**Comment by dbrgn** [comment]
> (And I think you mean "there are a few old-style classes"!)

Uh, yes, of course :/ Although they're regular classes in Python 3.

**Comment by ghickman** [comment]
@dbrgn – Encoding and `__future__` imports both sound great.

**Comment by dbrgn** [comment]
Added to #31.
